# Основные настройки
language: ru
settings:
  block-command-blocks: true

# Заблокированные команды
blocked-commands:
  - ban
  - ban-ip
  - banlist
  - kick
  - stop
  - op
  - deop
  - pardon
  - pardon-ip
  - whitelist
  - reload
  - restart
  - save-all
  - save-off
  - save-on
  - timings
  - kill

# Белый список
allowed-players:
  - Admin

# Локализации
messages:
  ru:
    op-grant: "&6Вы получили OP-статус с ограниченными правами!"
    command-blocked: "&cЭта команда заблокирована!"
    player-added: "&aИгрок %s добавлен в белый список!"
    player-exists: "&eЭтот игрок уже в белом списке!"
    no-permission: "&cНедостаточно прав!"
    usage: "&cИспользование: /allowplayer <ник>"
  
  en:
    op-grant: "&6You received OP with restrictions!"
    command-blocked: "&cThis command is blocked!"
    player-added: "&aPlayer %s added to whitelist!"
    player-exists: "&ePlayer already in whitelist!"
    no-permission: "&cNo permission!"
    usage: "&cUsage: /allowplayer <name>"

# Логирование
logging:
  console: true
  file: false
  max-file-size: 10MB